### ISSUE TITLE
[Bug]: App Not Running

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

I ran the APP to test the existing reports. Error returend  java: '}' expected" at line 35 in code. A Comma is missing. 

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
C:\Edinbuigh_Naper\Projects\SDEv\SeMethods\sem-project-group6\src\main\java\com\napier\seprojectgroup6\navigation\Navigator.java:35:91
java: '}' expected
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
bug has been Fixed.
