### ISSUE TITLE
[Bug]: Report 1; All Counties in the World missing columns

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

A country report requires the following columns:

Code.
Name.
Continent.
Region.
Population.
Capital.

Only Name, region and population listed. Columns headings need to be formatted correctly. Also should headline all counties in the world.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Select your report number or q to quit!
1
Countries In A Region By Population Size:
"name                                Region                                   population                      
China                               Eastern Asia                             1277558000                      
India                               Southern and Central Asia                1013662000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
Column Headers should be in CAPS.
