### ISSUE TITLE
[Bug]: REPORT 03, COUNTRIES IN A REGION. No region can be entered

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

1.There is no option to input region. Current report shows all regions. 
2. Titles need formatting in CAPS.  Current report doesn't display required output. See below the required fields to be displayed.
3. Screenshot Missing.
4. Update Met Requirements to YES

A country report requires the following columns:

Code.
Name.
Continent.
Region.
Population.
Capital.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Select your report number or q to quit!
1
Countries In A Region By Population Size:
"name                                Region                                   population                      
China                               Eastern Asia                             1277558000                      
India                               Southern and Central Asia                1013662000                      
United States                       North America                            278357000
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
This Report and UC06 are Similar and could be written in Once Class

**Comment by BobbyWal78** [comment]
Country Report
A country report requires the following columns:

Code.
Name.
Continent.
Region.
Population.
Capital.


No option to add region was  present when tested.
Name space has the be widen as well to accomodate large country name.
screen shot it also incorrect.

**Comment by BobbyWal78** [comment]
Issue fixed. BUG #233 need to be resolved
