### ISSUE TITLE
[Bug]: REPORT 04: Top Populated Countries In World; No Results

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

1. The is an option to enter a region which is not required.
2. Once region is entered, the results return empty.
3. Screenshot Missing.
4. Update Met Requirements to YES
### Version

Develop Branch

### Steps to Reproduce the Error

```shell
2
Enter N for the number of countries to display
10
Enter Name of Region
europe
Top 10 Populated Countries

Code       Name                      Continent            Region               Population           Capital
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sekonyela1** [comment]
This report has been merged with UC 1 and pushed
