### ISSUE TITLE
[Bug]: REPORT 07: ALL Cities In the World: Format issue

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

Column titles need formatting in ALL Caps

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
All the Cities In the World: 
City                                Country                                  District                       Population     
Mumbai (Bombay)                     India                                    Maharashtra                    10500000       
Seoul                               South Korea                              Seoul                          9981619        
São Paulo                           Brazil                                   São Paulo                      9968485
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
This Report and UC12 are Similar and can be written in Once Class

**Comment by BobbyWal78** [comment]
Columns  have been adjusted and fixed with another bug
