### ISSUE TITLE
[Bug]: REPORT 09: All Cities in Region

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

1.Output column titles need formatting to ALL CAPS
2. When ehe region , Eastern Asia was entered, the cities for the Caribbean are displayed.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Enter Region
Eastern Asia
All Cities by Region: Eastern Asia

City                                Country                                  District                       Population     
La Habana                           Cuba                                     La Habana                      2256000        
Santo Domingo de Guzmán             Dominican Republic                       Distrito Nacional              1609966        
Port-au-Prince                      Haiti                                    Ouest                          884472
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
This Report and UC14 are Similar and can be written in One Class
