### ISSUE TITLE
[Bug]: REPORT 02: All the countries in a continent: NOT FOUND

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

Missing Report All the countries in a continent.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
0: 01 Countries In World
1: 03 Countries In A Region By Population Size
2: 04 Top Populated Countries
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
This is already Covered in the TopPopulatedCountriesINAContinent Class. 
Both UC02 and UC05 Are covered
