### ISSUE TITLE
[Bug]: REPORT 12: Top N Cities by Population

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

1. Column titles need to be formatted.
2.  A city report requires the following columns:

Name.
Country.
District.
Population.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Enter N for the number of cities to display
5

Top 5 populated cities

City                 District   Population Country   
Mumbai (Bombay)      Maharashtra 10500000   India     
Seoul                Seoul      9981619    South Korea
São Paulo            São Paulo  9968485    Brazil    
Shanghai             Shanghai   9696300    China
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KelvinPompey-40718390** [comment]
@BobbyWal78  It seems this was removed from the menu due to duplicated functionality.

**Comment by BobbyWal78** [comment]
yes this issue was resolved in another issue
