### ISSUE TITLE
[Bug]: UC 30 Population of a District does not return any results.

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

When trying to return Results for a district, all come back with 0 values.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run Report for Total Population of a District.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
changes made to reflect required output.

**Comment by mikemmanuel** [comment]
Merged to Develop
