### ISSUE TITLE
[Bug]: UC 28 Population of Region not Showing Region Name in Report Output

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

Name of Region should be displayed in the Report Output.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run Total Population of a Region Report
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
Issue has been resolved. Prompt to enter region comes up, then output is shown based on the input.

**Comment by mikemmanuel** [comment]
Confirmation of print output. Region is displayed.
