### ISSUE TITLE
[Bug]: UC 27 Population of Continent not showing Continent in Report

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

The Name of continent is not being displayed in the Report Output.

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run Total Population of a Continent Report
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
Changes made to reflect desired output.

**Comment by mikemmanuel** [comment]
Merged to develop
