### ISSUE TITLE
[Bug]: UC26: Population of the World Is not Running

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

When running Population of the world, a error Message "Column Population not found. Failed to get population Details" is returned

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run Population of the World Report
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
Issue has been resolved. Output can be seen when the report is run.
