### ISSUE TITLE
[Bug]: UC17 and UC20  are Missing

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

Use Cases 17 and 20 are Missing from Application

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run App and observe Menu Listing
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
The respective reports have been added.
