### ISSUE TITLE
[Bug]: Project does not Create Jar File in IntelliJ

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

Project does not create Jar file 

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
Run Build on Maven.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BobbyWal78** [comment]
bug lost in sprint
