### ISSUE TITLE
[Bug]:  Missing Report Top N and All Populated Countries IN  the world

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

Missing is the TopN countries in the world. Merge counties in the world to get the Top N

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
00: 01 Countries In World
01: Top N and All Populated Countries by Region
02: Top N and All Populated Countries by Continent
03: Top N and All Populated Cities in The World
04: Top N and All Populated Cities by Continent
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
Duplicate issue See #173
