### ISSUE TITLE
[Bug]: No Integration Test for Population of a City Report

### ISSUE THREAD

**Issue by AntonJar-ENU** [KelvinPompey-40718390/sem-project-group6#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Anton

### Description of the bug?

No Integration Tests Defined

### Version

Develop Branch

### Steps to Reproduce the Error

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mikemmanuel** [comment]
Issue resolved with "feature/code-quality-tweaks"
