### ISSUE TITLE
[Bug]:  Report 2 output label incorrect

### ISSUE THREAD

**Issue by BobbyWal78** [KelvinPompey-40718390/sem-project-group6#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Name

Bobby Walters

### Description of the bug?

label incorrect

### Version

Develop Branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AntonJar-ENU** [comment]
Completed
